In [1]:
import numpy as np


In [2]:
myarr=np.array([2,4,5,6,9])


In [3]:
myarr

array([2, 4, 5, 6, 9])

## shape

In [4]:
a=np.array([[1,2,3],[3,6,7]])

In [5]:
a.shape

(2, 3)

## dtype

In [6]:
a.dtype

dtype('int32')

## size

In [7]:
a.size

6

## sort

In [8]:
b=np.array([[4,2,1,0],[8,5,9,6]])

In [9]:
b.sort()

In [10]:
b

array([[0, 1, 2, 4],
       [5, 6, 8, 9]])

## tolist

In [11]:
b.tolist()

[[0, 1, 2, 4], [5, 6, 8, 9]]

## append

In [12]:
c=np.array([[4,2],[3,2]])

In [13]:
np.append(c,8)

array([4, 2, 3, 2, 8])

## insert


In [14]:
np.insert(c,2,9)

array([4, 2, 9, 3, 2])

## Zeros

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ones

In [16]:
np.ones((8))

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Arange

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,2,dtype="float")

array([1., 3., 5., 7., 9.])

## linspace

In [20]:
np.linspace(1,10,num=6,endpoint=False,retstep=True)

(array([1. , 2.5, 4. , 5.5, 7. , 8.5]), 1.5)

In [21]:
np.linspace(1,10,num=5,endpoint=True)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## random

In [22]:
np.random.rand(2,5)

array([[0.62906817, 0.76627227, 0.26516616, 0.11776474, 0.97140082],
       [0.9634845 , 0.3004189 , 0.45113974, 0.55785124, 0.9578716 ]])

In [23]:
np.random.rand()

0.2223768639082513

## indexing on 1D array

In [24]:
p=np.array([1,2,3,4,5])
p[3]

4

In [25]:
p[-1]

5

## indexing on 2D array

In [26]:
l=np.array([[1,2],[3,4]])

In [27]:
l[1][1]

4

In [28]:
l[-2][0]

1

## indexing on 3D Array

In [29]:
m=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [30]:
m[0][0][1]

2

## slicing on 1D array

In [31]:
a=np.array([1,2,3,4,5,6])

In [32]:
a[0:5]

array([1, 2, 3, 4, 5])

In [33]:
a[::]

array([1, 2, 3, 4, 5, 6])

## slicing on 2D array

In [34]:
x=np.array([[1,2],[3,4],[5,6]])

In [35]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
x[1:,1:]

array([[4],
       [6]])

In [37]:
x[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

## slicing on 3D array

In [38]:
d=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [39]:
d[:,1:,::2]

array([[[ 5,  7],
        [ 9, 11]],

       [[17, 19],
        [21, 23]]])

## reshape

In [40]:
a=np.array([1,2,3,4,5,6])

In [41]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## resize

In [42]:
a=np.array([1,2,3,4,5,6])

In [43]:
np.resize(a,(5,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4]])

## flatten

In [44]:
l=np.array([[1,2],[3,4]])


In [45]:
l.flatten()

array([1, 2, 3, 4])

## operations on array

In [46]:
a=np.array([1,2,3,0])
b=np.array([3,4,5,6])

In [47]:
np.add(a,b)


array([4, 6, 8, 6])

In [48]:
np.subtract(a,b)

array([-2, -2, -2, -6])

In [49]:
np.multiply(a,b)

array([ 3,  8, 15,  0])

In [50]:
np.divide(a,b)

array([0.33333333, 0.5       , 0.6       , 0.        ])

In [51]:
np.argmin(a)

3

In [52]:
np.argmax(a)

2

In [53]:
np.max(b)

6

In [54]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 0.        ])